name: CI/CD Restaurante Software

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build do pacote Python
        run: python setup.py sdist bdist_wheel

  docker_build_and_push:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/restaurante-software:${{ github.sha }} .

      - name: Push da imagem
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/restaurante-software:${{ github.sha }}

  deploy:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy automático (exemplo com SSH)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USER }}/restaurante-software:${{ github.sha }}
            docker stop restaurante-software || true
            docker rm restaurante-software || true
            docker run -d --name restaurante-software \
              -e PYTHONPATH=/app/src \
              -p 80:80 \
              ${{ secrets.DOCKERHUB_USER }}/restaurante-software:${{ github.sha }}
