name: Build → Test → Publish

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t restaurante-software:ci-test .
      - run: docker run --rm restaurante-software:ci-test

  push_image:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e taguear imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/restaurante-software:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USER }}/restaurante-software:${{ github.sha }} \
                     ${{ secrets.DOCKERHUB_USER }}/restaurante-software:latest

      - name: Push para o registry
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/restaurante-software:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USER }}/restaurante-software:latest
