name: Build & Test Docker

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: docker build -t restaurante-software:latest .

      - name: Executar testes no container
        run: docker run --rm restaurante-software:latest
